### ISSUE TITLE
Remove unnecessary asterisks (*) in normalize.css

### ISSUE THREAD

**Issue by ghost** [rgylling/portfolio#10]
A lot of the comment sections have asterisks whose purpose I'm not sure of. The comments - and the file in general - would look cleaner if they were removed. Example:

Lines 93-95
`/**
- Improve readability when focused and also mouse hovered in all browsers.
  */`

Could be:

`/*
 Improve readability when focused and also mouse hovered in all browsers.
 */`

**Comment by rgylling** [comment]
This is a vendor library
