### ISSUE TITLE
Consider using ID's for targets of .click()

### ISSUE THREAD

**Issue by ghost** [rgylling/portfolio#11]
I realize the assignment encouraged us not to use IDs in favor of advanced CSS selectors - bravo doing that! But I can't help but think if you were to ever beef up your nav and/or decide to change the order around, your .click() functions wouldn't be attached to the specific li's you intended. Consider using IDs if you're up for living outside the (CF) law.

**Comment by rgylling** [comment]
As a part of the lab it was stated that we have to use css selectors rather then ids and classes
